# baseurl: "/Standaarden"
apiname: "VNG Standaarden Landingspagina"
url: "http://localhost:4000"

plugins:
  - jekyll-redirect-from
  - jekyll-remote-theme

remote_theme: VNG-Realisatie/jekyll-theme-vng-realisatie

github: VNG-Realisatie/Standaarden

theme: jekyll-theme-time-machine

project_name: VNG-Realisatie/Standaarden

